# This file is autogenerated. Instead of editing this file, please use the
# migrations feature of ActiveRecord to incrementally modify your database, and
# then regenerate this schema definition.

ActiveRecord::Schema.define(:version => 10) do

  create_table "accounts", :force => true do |t|
    t.column "name",   :string
    t.column "rights", :integer
  end

  create_table "checks", :force => true do |t|
    t.column "path",    :string,                     :null => false
    t.column "site_id", :integer,                    :null => false
    t.column "system",  :boolean, :default => false, :null => false
    t.column "active",  :boolean, :default => true,  :null => false
  end

  add_index "checks", ["site_id"], :name => "index_checks_on_site_id"

  create_table "helps", :force => true do |t|
    t.column "title",      :string
    t.column "position",   :integer
    t.column "content",    :text
    t.column "slug",       :string
    t.column "updated_at", :string
  end

  add_index "helps", ["slug"], :name => "index_helps_on_slug", :unique => true

  create_table "records", :force => true do |t|
    t.column "check_id",   :integer,  :null => false
    t.column "report_id",  :integer,  :null => false
    t.column "message",    :string,   :null => false
    t.column "status",     :integer,  :null => false
    t.column "length",     :integer,  :null => false
    t.column "body",       :string
    t.column "ok",         :boolean
    t.column "created_at", :datetime
  end

  add_index "records", ["check_id"], :name => "index_records_on_check_id"
  add_index "records", ["created_at"], :name => "index_records_on_created_at"

  create_table "reports", :force => true do |t|
    t.column "site_id",    :integer,  :null => false
    t.column "state",      :string,   :null => false
    t.column "mailed",     :boolean
    t.column "created_at", :datetime, :null => false
  end

  add_index "reports", ["site_id"], :name => "index_reports_on_site_id"
  add_index "reports", ["state"], :name => "index_reports_on_state"
  add_index "reports", ["created_at"], :name => "index_reports_on_created_at"

  create_table "rights", :force => true do |t|
    t.column "account_id", :integer
    t.column "user_id",    :integer
    t.column "rights",     :integer
  end

  add_index "rights", ["account_id", "user_id"], :name => "index_rights_on_account_id_and_user_id", :unique => true

  create_table "sessions", :force => true do |t|
    t.column "session_id", :string
    t.column "data",       :text
    t.column "updated_at", :datetime
  end

  add_index "sessions", ["session_id"], :name => "index_sessions_on_session_id"
  add_index "sessions", ["updated_at"], :name => "index_sessions_on_updated_at"

  create_table "sites", :force => true do |t|
    t.column "adress",       :string,   :null => false
    t.column "state",        :string,   :null => false
    t.column "account_id",   :integer,  :null => false
    t.column "updated_at",   :datetime
    t.column "last_checked", :datetime
  end

  add_index "sites", ["account_id"], :name => "index_sites_on_account_id"

  create_table "users", :force => true do |t|
    t.column "email",    :string,  :null => false
    t.column "password", :string,  :null => false
    t.column "token",    :string,  :null => false
    t.column "state",    :integer
    t.column "remember", :string
  end

  add_index "users", ["email"], :name => "index_users_on_email", :unique => true
  add_index "users", ["password"], :name => "index_users_on_password"
  add_index "users", ["remember"], :name => "index_users_on_remember"

end
